module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        scrollbarThumb: '#888',
        scrollbarTrack: '#f5f5f5',
      },
      fontFamily: {
        'roboto': ['Roboto', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
        'lato': ['Lato', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'montserrat': ['Montserrat', 'sans-serif'],
        'raleway': ['Raleway', 'sans-serif'],
        'nunito': ['Nunito', 'sans-serif'],
        'playfair-display': ['Playfair Display', 'serif'],
        'merriweather': ['Merriweather', 'serif'],
        'oswald': ['Oswald', 'sans-serif'],
        'source-sans-pro': ['Source Sans Pro', 'sans-serif'],
        'rubik': ['Rubik', 'sans-serif'],
        'dm-sans': ['DM Sans', 'sans-serif'],
        'public-sans': ['Public Sans', 'sans-serif'],
        'arial': ['Arial', 'sans-serif'],
        'verdana': ['Verdana', 'sans-serif'],
        'tahoma': ['Tahoma', 'sans-serif'],
        'times-new-roman': ['Times New Roman', 'serif'],
        'georgia': ['Georgia', 'serif'],
        'courier-new': ['Courier New', 'monospace'],
        'ubuntu': ['Ubuntu', 'sans-serif'],
        'raleway': ['Raleway', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'josefin-sans': ['Josefin Sans', 'sans-serif'],
        'fira-sans': ['Fira Sans', 'sans-serif'],
        'cabin': ['Cabin', 'sans-serif'],
        'quicksand': ['Quicksand', 'sans-serif'],
        'inconsolata': ['Inconsolata', 'monospace'],
        'pt-sans': ['PT Sans', 'sans-serif'],
        'work-sans': ['Work Sans', 'sans-serif'],
        'oxygen': ['Oxygen', 'sans-serif'],
        'raleway': ['Raleway', 'sans-serif'],
        'varela-round': ['Varela Round', 'sans-serif'],
        'alegreya': ['Alegreya', 'serif'],
        'saira': ['Saira', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('tailwind-scrollbar'),
  ],
};
